import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={inter.className}>
      <nav className="rounded-lg border border-gray-400 p-4 bg-gray-200">
        <Link href="/">Home</Link> | <Link href="/newpage">New Page</Link>
      </nav>

      <main>{children}</main>
    </div>
  );
}
